### ISSUE TITLE
When a user successfully signs up to the makerlog event from fixathon.io, we should redirect them back to fixathon.io and show a confirmation message

### ISSUE THREAD

**Issue by shylands** [impactmakers/fixathon#12]
@jpaulet What way do you think we should do this? Create a new page?

**Comment by jpaulet** [comment]
I created a new page that is a combination of 'landing' page but instead of:

    @include('partials.intro')
    @include('partials.about')
    @include('partials.prizes')
    @include('partials.judges')
    @include('partials.sponsors')
    @include('partials.becomeSponsor')
    @include('partials.participants')
    @include('partials.takePart')
    @include('partials.inspiration')
    @include('partials.registrationBanner')

its:

   @include('partials.intro')  << changed the text to 'Congratulations! You joined the ... '
    @include('partials.spread') << a banner like 'Register' in blue but with a 'Spread the word'
    @include('partials.faqContent') << The FAQ but with a different title 'How it works'
    @include('partials.inspiration')
    @include('partials.about')
    @include('partials.prizes')
    @include('partials.judges')
    @include('partials.participants')
    @include('partials.takePart')

You could only access this page if you registered to the event.
